platform:
  type: "napcat" # 消息平台，兼容 napcat, llonebot, lagrange
  http_host: "127.0.0.1" # HTTP 服务器 IP，非 docker 部署一般为 127.0.0.1，docker 部署一般为宿主机局域网 IP
  http_port: 2333 # HTTP 服务器端口
  api_token: "" # HTTP 服务器 token，没有则不填

api:
  - "https://api.xinyew.cn/api/douyinjx?url=" # 解析手机端分享链接 url示例: https://v.douyin.com/t_ToZGLYIBk
  - "https://api.suxun.site/api/douyin?url=" # 解析网页端视频链接 url示例: https://www.douyin.com/video/7488299765604666682
